# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-10 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20220710_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMChoice',
            new_name='UserChoiceAnswer',
        ),
        migrations.RenameField(
            model_name='userchoiceanswer',
            old_name='q_answer',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='userchoicequestionanswer',
            name='answer',
        ),
    ]
