# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-17 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_folder_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=80)),
            ],
        ),
    ]
