# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-30 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='upload\\images')),
            ],
        ),
    ]
