# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-31 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='note.ChoiceQuestion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='upload\\'),
        ),
    ]
