# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-08-07 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_auto_20220731_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='used_time',
            field=models.IntegerField(default=0),
        ),
    ]
